#!/bin/bash

# ObliviousGmn, June 2015
# https://github.com/ObliviousGmn
# Lemonbar Configs.. 

# Screen Width, For Panel ..
SW=`xrandr | grep current | awk '{print $8}'`

# Fonts
# FONT1="-misc-profont-medium-r-semicondensed--12-110-75-75-c-60-iso10646-1"
# FONT2="-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1"

# Icons ..
# ICON1="-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1"
# ICON2="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"

# Bedtime
ZZZ=12
zzz=4

# Panel
PWO=100
PW=$(( $SW - $PWO - $PWO ))
PH=25
PO=5

# Lemonpop
LW=220
LH=26
LX=1690
LY=45

# Sounds
Codec="aplay -q $HOME/Gmnbox/Sounds/metalgearcodec.wav"
Popup="aplay -q $HOME/Gmnbox/Sounds/popup.wav"
Beep="aplay -q $HOME/Gmnbox/Sounds/alarm.wav"
Camera="aplay -q $HOME/Gmnbox/Sounds/camera.wav"
Opps="aplay -q $HOME/Gmnbox/Sounds/opps.wav"
Whacha="aplay -q $HOME/Gmnbox/Sounds/whacha.wav"

# Color directory
CD="$CONFIGDIR/colors/frost"

# workspaces
WORKSPACES="HOME CODE WEB MEDIA"

bold=$(tput bold)
normal=$(tput sgr0)

# Fetch the Colors
BG=`cat ${CD} | grep -i background: | tail -c 8`
FG=`cat ${CD} | grep -i foreground: | tail -c 8`

BLACK=`cat ${CD} | grep -i color0: | tail -c 8`
BBLACK=`cat ${CD} | grep -i color8: | tail -c 8`

RED=`cat ${CD} | grep -i color1: | tail -c 8`
BRED=`cat ${CD} | grep -i color9: | tail -c 8`

GREEN=`cat ${CD} | grep -i color2: | tail -c 8`
BGREEN=`cat ${CD} | grep -i color10: | tail -c 8`

YELLOW=`cat ${CD} | grep -i color3: | tail -c 8`
BYELLOW=`cat ${CD} | grep -i color11: | tail -c 8`

BLUE=`cat ${CD} | grep -i color4: | tail -c 8`
BBLUE=`cat ${CD} | grep -i color12: | tail -c 8`

MAGENTA=`cat ${CD} | grep -i color5: | tail -c 8`
BMAGENTA=`cat ${CD} | grep -i color13: | tail -c 8`

CYAN=`cat ${CD} | grep -i color6: | tail -c 8`
BCYAN=`cat ${CD} | grep -i color14: | tail -c 8`

WHITE=`cat ${CD} | grep -i color7: | tail -c 8`
BWHITE=`cat ${CD} | grep -i color15: | tail -c 8`
