-- [[ init.lua ]]

-- Let's init the LazyVim plugin
require("config.options")
require("config.lazy")
-- This file defines colorscheme swapping methods
require("config.colorscheme")
-- This is an autogenerated file that contains the current colorscheme
-- based on what I've swapped automatically
require("config.current_colorscheme")

vim.api.nvim_create_autocmd("User", {
	pattern = "VeryLazy",
	callback = function()
		require("config.autocmds")
		require("config.keymaps")
	end,
})
